FROM python:3.12-slim

WORKDIR /app

COPY model-requirements.txt .

RUN pip install --no-cache-dir -r model-requirements.txt

EXPOSE 5001

CMD ["mlflow", "models", "serve", \
     "--model-uri", "models:/TitanicSurvivalModel@champion", \
     "--host", "0.0.0.0", \
     "--port", "5001", \
     "--env-manager", "local"]