import requests
import streamlit as st
import os

MODEL_URL = os.getenv(
    "MODEL_URL",
    "http://127.0.0.1:5001/invocations",
)

st.set_page_config(
    page_title="Titanic Survival Predictor",
    page_icon="🚢",
    layout="centered",
)


st.title("🚢 Titanic Survival Predictor")
st.write(
    "Enter passenger details and get a prediction "
    "from the MLflow-served model."
)


# ---------------------------------------------------------
# Passenger inputs
# ---------------------------------------------------------

st.subheader("Passenger Details")

pclass = st.selectbox(
    "Passenger Class",
    options=[1, 2, 3],
    index=2,
)

sex = st.selectbox(
    "Sex",
    options=["female", "male"],
)

age = st.number_input(
    "Age",
    min_value=0.0,
    max_value=100.0,
    value=22.0,
    step=1.0,
)

sibsp = st.number_input(
    "Number of Siblings/Spouses",
    min_value=0,
    max_value=10,
    value=0,
    step=1,
)

parch = st.number_input(
    "Number of Parents/Children",
    min_value=0,
    max_value=10,
    value=0,
    step=1,
)

fare = st.number_input(
    "Fare",
    min_value=0.0,
    max_value=600.0,
    value=32.0,
    step=0.5,
)

embarked = st.selectbox(
    "Port of Embarkation",
    options=["S", "C", "Q"],
)


# ---------------------------------------------------------
# Prediction
# ---------------------------------------------------------

if st.button("Predict Survival", type="primary"):

    passenger = {
        "Pclass": pclass,
        "Sex": sex,
        "Age": float(age),
        "SibSp": sibsp,
        "Parch": parch,
        "Fare": float(fare),
        "Embarked": embarked,
    }

    payload = {
        "dataframe_split": {
            "columns": list(passenger.keys()),
            "data": [list(passenger.values())],
        }
    }

    try:

        response = requests.post(
            MODEL_URL,
            json=payload,
            timeout=10,
        )

        response.raise_for_status()

        result = response.json()

        prediction = result["predictions"][0]

        st.divider()

        st.subheader("Prediction")

        if prediction == 1:
            st.success("Prediction: Survived")
        else:
            st.error("Prediction: Did not survive")

        st.caption(
            "Prediction generated by the MLflow champion model."
        )

    except requests.exceptions.ConnectionError:

        st.error(
            "Could not connect to the MLflow model server. "
            "Make sure the model server is running on port 5001."
        )

    except requests.exceptions.RequestException as e:

        st.error(f"Model server error: {e}")